-- AfriFINOS domain IDs are opaque strings, not UUID-only values.
-- Drop dependent foreign keys before changing UUID-backed identifiers to TEXT.

ALTER TABLE accounts DROP CONSTRAINT accounts_owner_id_fkey;
ALTER TABLE accounts DROP CONSTRAINT accounts_provider_id_fkey;
ALTER TABLE categories DROP CONSTRAINT categories_owner_id_fkey;
ALTER TABLE categories DROP CONSTRAINT categories_parent_id_fkey;
ALTER TABLE transactions DROP CONSTRAINT transactions_owner_id_fkey;
ALTER TABLE transactions DROP CONSTRAINT transactions_category_id_fkey;
ALTER TABLE transactions DROP CONSTRAINT transactions_provider_id_fkey;
ALTER TABLE ledger_entries DROP CONSTRAINT ledger_entries_transaction_id_fkey;
ALTER TABLE ledger_entries DROP CONSTRAINT ledger_entries_account_id_fkey;
ALTER TABLE assets DROP CONSTRAINT assets_owner_id_fkey;
ALTER TABLE liabilities DROP CONSTRAINT liabilities_owner_id_fkey;
ALTER TABLE obligations DROP CONSTRAINT obligations_owner_id_fkey;
ALTER TABLE savings_goals DROP CONSTRAINT savings_goals_owner_id_fkey;
ALTER TABLE provider_balance_observations DROP CONSTRAINT provider_balance_observations_account_id_fkey;
ALTER TABLE provider_balance_observations DROP CONSTRAINT provider_balance_observations_provider_id_fkey;
ALTER TABLE transaction_imports DROP CONSTRAINT transaction_imports_owner_id_fkey;
ALTER TABLE transaction_imports DROP CONSTRAINT transaction_imports_provider_id_fkey;

ALTER TABLE users ALTER COLUMN id DROP DEFAULT;
ALTER TABLE users ALTER COLUMN id TYPE TEXT USING id::text;
ALTER TABLE providers ALTER COLUMN id DROP DEFAULT;
ALTER TABLE providers ALTER COLUMN id TYPE TEXT USING id::text;
ALTER TABLE accounts ALTER COLUMN id DROP DEFAULT;
ALTER TABLE accounts ALTER COLUMN id TYPE TEXT USING id::text;
ALTER TABLE accounts ALTER COLUMN owner_id TYPE TEXT USING owner_id::text;
ALTER TABLE accounts ALTER COLUMN provider_id TYPE TEXT USING provider_id::text;
ALTER TABLE categories ALTER COLUMN owner_id TYPE TEXT USING owner_id::text;
ALTER TABLE categories ALTER COLUMN parent_id TYPE TEXT USING parent_id::text;
ALTER TABLE transactions ALTER COLUMN id DROP DEFAULT;
ALTER TABLE transactions ALTER COLUMN id TYPE TEXT USING id::text;
ALTER TABLE transactions ALTER COLUMN owner_id TYPE TEXT USING owner_id::text;
ALTER TABLE transactions ALTER COLUMN category_id TYPE TEXT USING category_id::text;
ALTER TABLE transactions ALTER COLUMN provider_id TYPE TEXT USING provider_id::text;
ALTER TABLE ledger_entries ALTER COLUMN id DROP DEFAULT;
ALTER TABLE ledger_entries ALTER COLUMN transaction_id TYPE TEXT USING transaction_id::text;
ALTER TABLE ledger_entries ALTER COLUMN account_id TYPE TEXT USING account_id::text;
ALTER TABLE assets ALTER COLUMN id DROP DEFAULT;
ALTER TABLE assets ALTER COLUMN id TYPE TEXT USING id::text;
ALTER TABLE assets ALTER COLUMN owner_id TYPE TEXT USING owner_id::text;
ALTER TABLE liabilities ALTER COLUMN id DROP DEFAULT;
ALTER TABLE liabilities ALTER COLUMN id TYPE TEXT USING id::text;
ALTER TABLE liabilities ALTER COLUMN owner_id TYPE TEXT USING owner_id::text;
ALTER TABLE obligations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE obligations ALTER COLUMN id TYPE TEXT USING id::text;
ALTER TABLE obligations ALTER COLUMN owner_id TYPE TEXT USING owner_id::text;
ALTER TABLE savings_goals ALTER COLUMN id DROP DEFAULT;
ALTER TABLE savings_goals ALTER COLUMN id TYPE TEXT USING id::text;
ALTER TABLE savings_goals ALTER COLUMN owner_id TYPE TEXT USING owner_id::text;
ALTER TABLE provider_balance_observations ALTER COLUMN id DROP DEFAULT;
ALTER TABLE provider_balance_observations ALTER COLUMN account_id TYPE TEXT USING account_id::text;
ALTER TABLE provider_balance_observations ALTER COLUMN provider_id TYPE TEXT USING provider_id::text;
ALTER TABLE transaction_imports ALTER COLUMN id DROP DEFAULT;
ALTER TABLE transaction_imports ALTER COLUMN owner_id TYPE TEXT USING owner_id::text;
ALTER TABLE transaction_imports ALTER COLUMN provider_id TYPE TEXT USING provider_id::text;

ALTER TABLE accounts ADD CONSTRAINT accounts_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE accounts ADD CONSTRAINT accounts_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE SET NULL;
ALTER TABLE categories ADD CONSTRAINT categories_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE categories ADD CONSTRAINT categories_parent_id_fkey FOREIGN KEY (parent_id) REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE transactions ADD CONSTRAINT transactions_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE transactions ADD CONSTRAINT transactions_category_id_fkey FOREIGN KEY (category_id) REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE transactions ADD CONSTRAINT transactions_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE SET NULL;
ALTER TABLE ledger_entries ADD CONSTRAINT ledger_entries_transaction_id_fkey FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE RESTRICT;
ALTER TABLE ledger_entries ADD CONSTRAINT ledger_entries_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE RESTRICT;
ALTER TABLE assets ADD CONSTRAINT assets_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE liabilities ADD CONSTRAINT liabilities_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE obligations ADD CONSTRAINT obligations_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE savings_goals ADD CONSTRAINT savings_goals_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE provider_balance_observations ADD CONSTRAINT provider_balance_observations_account_id_fkey FOREIGN KEY (account_id) REFERENCES accounts(id) ON DELETE CASCADE;
ALTER TABLE provider_balance_observations ADD CONSTRAINT provider_balance_observations_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE SET NULL;
ALTER TABLE transaction_imports ADD CONSTRAINT transaction_imports_owner_id_fkey FOREIGN KEY (owner_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE transaction_imports ADD CONSTRAINT transaction_imports_provider_id_fkey FOREIGN KEY (provider_id) REFERENCES providers(id) ON DELETE SET NULL;
